version: "3.8"
services:
  flashcards:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashcards-app
    stdin_open: true   # Aktiviert interaktiven Modus (für Eingaben)
    tty: true          # Ermöglicht ein TTY (Terminal)
